# Run indexer
name: Mainnet Indexer
on:
  repository_dispatch:
    types:
      - index
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: bootstrap
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        PKG: ${{ github.event.client_payload.pkg }}
        CODE: ${{ github.event.client_payload.code }}
      run: |
        printf "%s" "$PKG" > package.json      
        printf "%s" "$CODE" > index.js
        node index.js
